<a href="https://colab.research.google.com/github/vcnzx/Machine_Learning_Project/blob/main/SPA_Wine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Spanish Wine Quality Prediction
Author: Charlie Ventura

##Import Libraries

In [2]:
## Pandas
import pandas as pd
## Numpy
import numpy as np
## MatPlotLib
import matplotlib.pyplot as plt

##Load Data

In [3]:
fpath = '/content/drive/MyDrive/CodingDojo/02-MachineLearning/Week08/Data/wines_SPA.csv'
df = pd.read_csv(fpath)

##Inspect Data

In [4]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   winery       7500 non-null   object
 1   wine         7500 non-null   object
 2   year         7498 non-null   object
 3   rating       7500 non-null   float64
 4   num_reviews  7500 non-null   int64
 5   country      7500 non-null   object
 6   region       7500 non-null   object
 7   price        7500 non-null   float64
 8   type         6955 non-null   object
 9   body         6331 non-null   float64
 10  acidity      6331 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 644.7+ KB

,winery,wine,year,rating,num_reviews,country,region,price,type,body,acidity
0,Teso La Monja,Tinto,2013,4.9,58,Espana,Toro,995.00,Toro Red,5.0,3.0
1,Artadi,Vina El Pison,2018,4.9,31,Espana,Vino de Espana,313.50,Tempranillo,4.0,2.0
2,Vega Sicilia,Unico,2009,4.8,1793,Espana,Ribera del Duero,324.95,Ribera Del Duero Red,5.0,3.0
3,Vega Sicilia,Unico,1999,4.8,1705,Espana,Ribera del Duero,692.96,Ribera Del Duero Red,5.0,3.0
4,Vega Sicilia,Unico,1996,4.8,1309,Espana,Ribera del Duero,778.06,Ribera Del Duero Red,5.0,3.0

##First choice:

1. Source of data
- https://www.kaggle.com/datasets/fedesoriano/spanish-wine-quality-dataset?resource=download
2. Brief description of data
- Data set of spanish red wine.

3. What is the target?
- Rating

4. What does one row represent? (A person? A business? An event? A product?)
- A product: red wine
5. Is this a classification or regression problem?
- Regression
6. How many features does the data have?
- 10
7. How many rows are in the dataset?
- 7500
8. What, if any, challenges do you foresee in cleaning, exploring, or modeling this dataset?
- There are a lot of missing values for some of the features